Algoritmo "Crescente"
// Problema "Crescente" - Estrutura repetitiva Enquanto
Var

   x, y : inteiro

Inicio

   escreval("Digite dois números:")
   leia(x)
   leia(y)
   enquanto x <> y faca
      se x > y entao
         escreval("Os números estão em ordem decrescente!")
      senao
         escreval("Os números estão em ordem crescente!")
      fimse
      escreval("Digite outros dois números:")
      leia(x)
      leia(y)
   fimenquanto

Fimalgoritmo